insert
	into
	transaction_type (transaction_type_descr)
values ('Rent'),
('Gas'),
('Electric'),
('Cable'),
('Internet'),
('Phones'),
('Insurnace'),
('Mortgage'),
('Grcoeries'),
('Restaurant'),
('School Supplies'),
('Social'),
('Vacation'),
('Oil Change'),
('Brakes'),
('Bumper'),
('Car Detail'),
('General Maintanance'),
('Collision Maintenance'),
('Medical Copay'),
('Prescription Payment'),
('Amazon')